requireTitle: true
requireCommits: 'all'
requirePrBreakingChangeColon: true
requireCommitBreakingChangeColon: true
requireJira: false
allowedScopes:
  - 'cli'
  - 'directives'
  - 'scalars'
  - 'transformers'
